apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Darling\Desktop\新建文件夹\kompose-windows-amd64.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  ports:
    - name: "4560"
      port: 4560
      targetPort: 4560
  selector:
    io.kompose.service: logstash
status:
  loadBalancer: {}
